### ISSUE TITLE
UnicodeDecodeError on Kali

### ISSUE THREAD

**Issue by CalfCrusher** [TarlogicSecurity/kerbrute#7]
I'm unable to run kerbrute, neither with python3 or python3.9, i got:

Impacket v0.9.23 - Copyright 2021 SecureAuth Corporation

```
Traceback (most recent call last):
  File "/home/kali/kerbrute/kerbrute.py", line 4, in <module>
    kerbrute.main()
  File "/home/kali/kerbrute/kerbrute/main.py", line 100, in main
    args = parser.parse_args()
  File "/home/kali/kerbrute/kerbrute/main.py", line 80, in parse_args
    args.passwords = self._get_file_lines(args.passwords)
  File "/home/kali/kerbrute/kerbrute/main.py", line 92, in _get_file_lines
    return [line.strip('\r\n') for line in fi]
  File "/home/kali/kerbrute/kerbrute/main.py", line 92, in <listcomp>
    return [line.strip('\r\n') for line in fi]
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 933: invalid continuation byte
```

Also installing through pip i get same error :-(

**Comment by CalfCrusher** [comment]
For strange reasons problem occurs only on rockyou.txt wordlist, other file works. I'll close, thanks :)
